Added Check Azure Secrets code block in terraform yaml file

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -39,6 +39,14 @@ jobs:
         with:
           terraform_version: 1.12.2
 
+      - name: Check Azure Secrets
+        shell: bash
+        run: |
+          test -n "$ARM_CLIENT_ID" && echo "ARM_CLIENT_ID present" || echo "ARM_CLIENT_ID MISSING"
+          test -n "$ARM_CLIENT_SECRET" && echo "ARM_CLIENT_SECRET present" || echo "ARM_CLIENT_SECRET MISSING"
+          test -n "$ARM_TENANT_ID" && echo "ARM_TENANT_ID present" || echo "ARM_TENANT_ID MISSING"
+          test -n "$ARM_SUBSCRIPTION_ID" && echo "ARM_SUBSCRIPTION_ID present" || echo "ARM_SUBSCRIPTION_ID MISSING"
+
       - name: Terraform Init
         run: terraform init
 
